// ====================================================================================================================
// TODO:  "PRODUCTS.JS" IS AN ARRAY OF OBJECTS WITH EACH OBJECT REPRESENTING A PRODUCT LISTED ON THE E-COMMERCE STORE
// ====================================================================================================================

const products = [
  // ==================================================================================================================
  // FIXME:  LISTED PRODUCTS IN THIS CATEGORY
  // ==================================================================================================================

  // =========================
  // TODO:  PRODUCT 001  TODO:
  // =========================

  {
    PRODUCT_ID: 0,
    WEBP_IMAGE_1: ".images/image_filename_1.webp",
    WEBP_IMAGE_2: ".images/image_filename_2.webp",
    WEBP_IMAGE_3: ".images/image_filename_3.webp",
    WEBP_IMAGE_4: ".images/image_filename_4.webp",
    WEBP_IMAGE_BRAND: ".images/logo_file_name.webp",
    CATEGORY_LEVEL_1_NUMBER: "ENTER NUMBER HERE",
    CATEGORY_LEVEL_1_NAME: "ENTER HERE",
    CATEGORY_LEVEL_2_NUMBER: "ENTER NUMBER HERE",
    CATEGORY_LEVEL_2_NAME: "ENTER HERE",
    CATEGORY_LEVEL_3_NUMBER: "ENTER NUMBER HERE",
    CATEGORY_LEVEL_3_NAME: "ENTER HERE",
    CATEGORY_LEVEL_4_NUMBER: "ENTER NUMBER HERE",
    CATEGORY_LEVEL_4_NAME: "ENTER HERE",
    CATEGORY_LEVEL_5_NUMBER: "ENTER NUMBER HERE",
    CATEGORY_LEVEL_5_NAME: "ENTER HERE",
    SHOW_PRODUCT_ON_SITE: "NO",
    SHOW_PRICE_ON_SITE: "NO",
    PRODUCT_ON_SALE: "NO",
    PRODUCT_NEW_ARRIVAL: "NO",
    PRODUCT_TITLE: "Short product tile here",
    PRODUCT_INFO_BRIEF: "Brief product description here",
    PRODUCT_INFO_FULL: "Detailed product description here",
    PRODUCT_BRAND: "BRAND NAME HERE",
    PRODUCT_SKU: "PRODUCT-ID HERE",
    PRODUCT_MODEL: "MODEL NUMBER HERE",
    PRODUCT_STOCK: 0,
    PRODUCT_LENGTH_CM: 0,
    PRODUCT_WIDTH_CM: 0,
    PRODUCT_HEIGHT_CM: 0,
    PRODUCT_WEIGHT_KG: 0,
    SHIPPING_VOLUMETRIC_FACTOR: 5000,
    SHIPPING_VOLUMETRIC_WEIGHT_KG: 0,
    SHIPPING_FINAL_WEIGHT_KG: 0,
    PRODUCT_SELLING_CURRENCY: "R",
    PRODUCT_SELLING_PRICE: 0,
  },

  // =========================
  // TODO:  PRODUCT 002  TODO:
  // =========================

  {
    id: 1,
    imgSrc1: ".images/macbook_pro_16_01.webp",
    imgSrc2: ".images/macbook_pro_16_02.webp",
    imgSrc3: ".images/macbook_pro_16_03.webp",
    imgSrc4: ".images/macbook_pro_16_04.webp",
    productTitle: "APPLE MACBOOK M1 PRO 16",
    productDescriptionBrief:
      "Apple Macbook M1 Pro Laptop - 16” Liquid Retina XDR display, 16GB, 1TB SSD, Space Grey",
    currency: "R",
    productSellingPrice: 52299,
    imgSrcBrand: ".images/logo_apple.webp",
    productBrand: "Apple",
    productSku: "MacP16-1TB",
    productModel: "MacP16-1TB",
    itemsInStock: 4,
    LengthCm: 24.81,
    widthCm: 35.57,
    heightCm: 1.68,
    weightKg: 2.1,
    productDescriptionFull:
      "Apple Macbook M1 Pro Laptop. CPU: ; GPU: ; SIM: ; SCREEN: ; MEMORY: ; STORAGE: ; EXTERNAL STORAGE: ; CAMERA(BACK): ; CAMERA(FRONT): ; CONNECTIVITY: ; OTHER/SENSORS: ; BATTERY: ; OPERATING SYSTEM: ; WARRANTY: ; COLOR: ; OPTIONAL: ",
    showProductOnSite: "NO",
    showPriceOnSite: "NO",
    itemOnSale: "NO",
    itemNewArrival: "NO",
    mainProductCategoryNr: "ENTER NUMBER HERE",
    mainProductCategoryTitle: "ENTER HERE",
    levelOneProductCategoryNr: "ENTER NUMBER HERE",
    levelOneProductCategoryTitle: "ENTER HERE",
    levelTwoProductCategoryNr: "ENTER NUMBER HERE",
    levelTwoProductCategoryTitle: "ENTER HERE",
    levelThreeProductCategoryNr: "ENTER NUMBER HERE",
    levelThreeProductCategoryTitle: "ENTER HERE",
    levelFourProductCategoryNr: "ENTER NUMBER HERE",
    levelFourProductCategoryTitle: "ENTER HERE",
    levelFiveProductCategoryNr: "ENTER NUMBER HERE",
    levelFiveProductCategoryTitle: "ENTER HERE",
  },

  // =========================
  // TODO:  PRODUCT 003  TODO:
  // =========================

  {
    id: 2,
    imgSrc1: ".images/dell_32_4k_monitor_01.webp",
    imgSrc2: ".images/dell_32_4k_monitor_02.webp",
    imgSrc3: ".images/dell_32_4k_monitor_03.webp",
    imgSrc4: ".images/dell_32_4k_monitor_04.webp",
    productTitle: "DELL 32” 4K MONITOR",
    productDescriptionBrief:
      "Dell UltraSharp 32” 4K Monitor (U3219Q) – Black, DisplayPort, HDMI, USB-C, USB 3.0",
    currency: "R",
    productSellingPrice: 16500,
    imgSrcBrand: ".images/logo_dell.webp",
    productBrand: "Dell",
    productSku: "U3219Q",
    productModel: "U3219Q",
    itemsInStock: 2,
    LengthCm: 46.87,
    widthCm: 71.25,
    heightCm: 22,
    weightKg: 5.8,
    productDescriptionFull:
      "Dell UltraSharp 32” Black 4K Monitor (U3219Q). CPU: ; GPU: ; SIM: ; SCREEN: ; MEMORY: ; STORAGE: ; EXTERNAL STORAGE: ; CAMERA(BACK): ; CAMERA(FRONT): ; CONNECTIVITY: ; OTHER/SENSORS: ; BATTERY: ; OPERATING SYSTEM: ; WARRANTY: ; COLOR: ; OPTIONAL: ",
    showProductOnSite: "NO",
    showPriceOnSite: "NO",
    itemOnSale: "NO",
    itemNewArrival: "NO",
    mainProductCategoryNr: "ENTER NUMBER HERE",
    mainProductCategoryTitle: "ENTER HERE",
    levelOneProductCategoryNr: "ENTER NUMBER HERE",
    levelOneProductCategoryTitle: "ENTER HERE",
    levelTwoProductCategoryNr: "ENTER NUMBER HERE",
    levelTwoProductCategoryTitle: "ENTER HERE",
    levelThreeProductCategoryNr: "ENTER NUMBER HERE",
    levelThreeProductCategoryTitle: "ENTER HERE",
    levelFourProductCategoryNr: "ENTER NUMBER HERE",
    levelFourProductCategoryTitle: "ENTER HERE",
    levelFiveProductCategoryNr: "ENTER NUMBER HERE",
    levelFiveProductCategoryTitle: "ENTER HERE",
  },

  // =========================
  // TODO:  PRODUCT 004  TODO:
  // =========================

  {
    id: 3,
    imgSrc1: ".images/dell_xps_15_9520_01.webp",
    imgSrc2: ".images/dell_xps_15_9520_02.webp",
    imgSrc3: ".images/dell_xps_15_9520_03.webp",
    imgSrc4: ".images/dell_xps_15_9520_04.webp",
    productTitle: "DELL XPS 15 9520 LAPTOP",
    productDescriptionBrief:
      "Dell XPS 15 9520 Laptop – Platinum Silver, Core i7, 15.6” FHD, 32GB, 1TB SSD, Win 11 Pro, Nvidia GeForce 3050 Ti (4GB)",
    currency: "R",
    productSellingPrice: 48500,
    imgSrcBrand: ".images/logo_dell.webp",
    productBrand: "Dell",
    productSku: "XPS-15-9520",
    productModel: "XPS-15-9520",
    itemsInStock: 6,
    LengthCm: 23.01,
    widthCm: 34.44,
    heightCm: 1.854,
    weightKg: 2.1,
    productDescriptionFull:
      "Dell XPS 15 9520 Laptop (XPS15-I712700H-321TBP). CPU: ; GPU: ; SIM: ; SCREEN: ; MEMORY: ; STORAGE: ; EXTERNAL STORAGE: ; CAMERA(BACK): ; CAMERA(FRONT): ; CONNECTIVITY: ; OTHER/SENSORS: ; BATTERY: ; OPERATING SYSTEM: ; WARRANTY: ; COLOR: ; OPTIONAL: ",
    showProductOnSite: "NO",
    showPriceOnSite: "NO",
    itemOnSale: "NO",
    itemNewArrival: "NO",
    mainProductCategoryNr: "ENTER NUMBER HERE",
    mainProductCategoryTitle: "ENTER HERE",
    levelOneProductCategoryNr: "ENTER NUMBER HERE",
    levelOneProductCategoryTitle: "ENTER HERE",
    levelTwoProductCategoryNr: "ENTER NUMBER HERE",
    levelTwoProductCategoryTitle: "ENTER HERE",
    levelThreeProductCategoryNr: "ENTER NUMBER HERE",
    levelThreeProductCategoryTitle: "ENTER HERE",
    levelFourProductCategoryNr: "ENTER NUMBER HERE",
    levelFourProductCategoryTitle: "ENTER HERE",
    levelFiveProductCategoryNr: "ENTER NUMBER HERE",
    levelFiveProductCategoryTitle: "ENTER HERE",
  },

  // =========================
  // TODO:  PRODUCT 005  TODO:
  // =========================

  {
    id: 4,
    imgSrc1: ".images/hp_pc_bundle_01.webp",
    imgSrc2: ".images/hp_pc_bundle_02.webp",
    imgSrc3: ".images/hp_pc_bundle_03.webp",
    imgSrc4: ".images/hp_pc_bundle_04.webp",
    productTitle: "HP PC & MONITOR BUNDLE",
    productDescriptionBrief:
      "HP 290 G4 Micro Tower Desktop PC and HP P24V G4 24” Full HD Monitor Bundle (Windows 11 Pro)",
    currency: "R",
    productSellingPrice: 15500,
    imgSrcBrand: ".images/logo_hp.webp",
    productBrand: "HP",
    productSku: "5W6D3EA",
    productModel: "5W6D3EA",
    itemsInStock: 10,
    LengthCm: 30.3,
    widthCm: 33.7,
    heightCm: 15.5,
    weightKg: 4.7,
    productDescriptionFull:
      "HP 290 G4 Micro Tower Desktop PC and HP P24V G4 24” Full HD Monitor Bundle (5W6D3EA). CPU: ; GPU: ; SIM: ; SCREEN: ; MEMORY: ; STORAGE: ; EXTERNAL STORAGE: ; CAMERA(BACK): ; CAMERA(FRONT): ; CONNECTIVITY: ; OTHER/SENSORS: ; BATTERY: ; OPERATING SYSTEM: ; WARRANTY: ; COLOR: ; OPTIONAL: ",
    showProductOnSite: "NO",
    showPriceOnSite: "NO",
    itemOnSale: "NO",
    itemNewArrival: "NO",
    mainProductCategoryNr: "ENTER NUMBER HERE",
    mainProductCategoryTitle: "ENTER HERE",
    levelOneProductCategoryNr: "ENTER NUMBER HERE",
    levelOneProductCategoryTitle: "ENTER HERE",
    levelTwoProductCategoryNr: "ENTER NUMBER HERE",
    levelTwoProductCategoryTitle: "ENTER HERE",
    levelThreeProductCategoryNr: "ENTER NUMBER HERE",
    levelThreeProductCategoryTitle: "ENTER HERE",
    levelFourProductCategoryNr: "ENTER NUMBER HERE",
    levelFourProductCategoryTitle: "ENTER HERE",
    levelFiveProductCategoryNr: "ENTER NUMBER HERE",
    levelFiveProductCategoryTitle: "ENTER HERE",
  },

  // =========================
  // TODO:  PRODUCT 006  TODO:
  // =========================

  {
    id: 5,
    imgSrc1: ".images/hp_zbook_fury_15_g8_01.webp",
    imgSrc2: ".images/hp_zbook_fury_15_g8_02.webp",
    imgSrc3: ".images/hp_zbook_fury_15_g8_03.webp",
    imgSrc4: ".images/hp_zbook_fury_15_g8_04.webp",
    productTitle: "HP ZBOOK FURY 15 G8",
    productDescriptionBrief:
      "HP Zbook Fury 15 G8 Laptop – Core i9, 15.6” FHD, 32GB, 1TB SSD, NVIDIA® RTX A3000 GDDR6 (6GB), Windows 11 Pro",
    currency: "R",
    productSellingPrice: 61500,
    imgSrcBrand: ".images/logo_hp.webp",
    productBrand: "HP",
    productSku: "62T88EA",
    productModel: "62T88EA",
    itemsInStock: 3,
    LengthCm: 24.26,
    widthCm: 36.09,
    heightCm: 2.59,
    weightKg: 2.35,
    productDescriptionFull:
      "HP Zbook Fury 15 G8 Laptop (62T88EA). CPU: ; GPU: ; SIM: ; SCREEN: ; MEMORY: ; STORAGE: ; EXTERNAL STORAGE: ; CAMERA(BACK): ; CAMERA(FRONT): ; CONNECTIVITY: ; OTHER/SENSORS: ; BATTERY: ; OPERATING SYSTEM: ; WARRANTY: ; COLOR: ; OPTIONAL: ",
    showProductOnSite: "NO",
    showPriceOnSite: "NO",
    itemOnSale: "NO",
    itemNewArrival: "NO",
    mainProductCategoryNr: "ENTER NUMBER HERE",
    mainProductCategoryTitle: "ENTER HERE",
    levelOneProductCategoryNr: "ENTER NUMBER HERE",
    levelOneProductCategoryTitle: "ENTER HERE",
    levelTwoProductCategoryNr: "ENTER NUMBER HERE",
    levelTwoProductCategoryTitle: "ENTER HERE",
    levelThreeProductCategoryNr: "ENTER NUMBER HERE",
    levelThreeProductCategoryTitle: "ENTER HERE",
    levelFourProductCategoryNr: "ENTER NUMBER HERE",
    levelFourProductCategoryTitle: "ENTER HERE",
    levelFiveProductCategoryNr: "ENTER NUMBER HERE",
    levelFiveProductCategoryTitle: "ENTER HERE",
  },

  // =========================
  // TODO:  PRODUCT 007  TODO:
  // =========================

  {
    id: 6,
    imgSrc1: ".images/huawei_matebook_x_pro_01.webp",
    imgSrc2: ".images/huawei_matebook_x_pro_02.webp",
    imgSrc3: ".images/huawei_matebook_x_pro_03.webp",
    imgSrc4: ".images/huawei_matebook_x_pro_04.webp",
    productTitle: "HUAWEI MATEBOOK X PRO",
    productDescriptionBrief:
      "Huawei Matebook X Pro Laptop – Core i7, 13.9” Touch Display, 16GB, 1TB SSD, Windows 10 Pro (Free Upgrade to 11)",
    currency: "R",
    productSellingPrice: 29000,
    imgSrcBrand: ".images/logo_huawei.webp",
    productBrand: "Huawei",
    productSku: "MateXPro",
    productModel: "MateXPro",
    itemsInStock: 6,
    LengthCm: 21.7,
    widthCm: 30.4,
    heightCm: 1.46,
    weightKg: 1.33,
    productDescriptionFull:
      "Huawei Matebook X Pro Laptop. CPU: ; GPU: ; SIM: ; SCREEN: ; MEMORY: ; STORAGE: ; EXTERNAL STORAGE: ; CAMERA(BACK): ; CAMERA(FRONT): ; CONNECTIVITY: ; OTHER/SENSORS: ; BATTERY: ; OPERATING SYSTEM: ; WARRANTY: ; COLOR: ; OPTIONAL: ",
    showProductOnSite: "NO",
    showPriceOnSite: "NO",
    itemOnSale: "NO",
    itemNewArrival: "NO",
    mainProductCategoryNr: "ENTER NUMBER HERE",
    mainProductCategoryTitle: "ENTER HERE",
    levelOneProductCategoryNr: "ENTER NUMBER HERE",
    levelOneProductCategoryTitle: "ENTER HERE",
    levelTwoProductCategoryNr: "ENTER NUMBER HERE",
    levelTwoProductCategoryTitle: "ENTER HERE",
    levelThreeProductCategoryNr: "ENTER NUMBER HERE",
    levelThreeProductCategoryTitle: "ENTER HERE",
    levelFourProductCategoryNr: "ENTER NUMBER HERE",
    levelFourProductCategoryTitle: "ENTER HERE",
    levelFiveProductCategoryNr: "ENTER NUMBER HERE",
    levelFiveProductCategoryTitle: "ENTER HERE",
  },

  // =========================
  // TODO:  PRODUCT 008  TODO:
  // =========================

  {
    id: 7,
    imgSrc1: ".images/huawei_mateview_gt_01.webp",
    imgSrc2: ".images/huawei_mateview_gt_02.webp",
    imgSrc3: ".images/huawei_mateview_gt_03.webp",
    imgSrc4: ".images/huawei_mateview_gt_04.webp",
    productTitle: "HUAWEI MATEVIEW GT",
    productDescriptionBrief:
      "Huawei MateView GT – Premium 34” Sound-Edition Display with integrated SoundBar (Blue Light and Flicker Free Certified)",
    currency: "R",
    productSellingPrice: 12000,
    imgSrcBrand: ".images/logo_huawei.webp",
    productBrand: "Huawei",
    productSku: "MateViewGT",
    productModel: "MateViewGT",
    itemsInStock: 5,
    LengthCm: 54.2,
    widthCm: 80.86,
    heightCm: 22,
    weightKg: 9.5,
    productDescriptionFull:
      "Huawei MateView GT. CPU: ; GPU: ; SIM: ; SCREEN: ; MEMORY: ; STORAGE: ; EXTERNAL STORAGE: ; CAMERA(BACK): ; CAMERA(FRONT): ; CONNECTIVITY: ; OTHER/SENSORS: ; BATTERY: ; OPERATING SYSTEM: ; WARRANTY: ; COLOR: ; OPTIONAL: ",
    showProductOnSite: "NO",
    showPriceOnSite: "NO",
    itemOnSale: "NO",
    itemNewArrival: "NO",
    mainProductCategoryNr: "ENTER NUMBER HERE",
    mainProductCategoryTitle: "ENTER HERE",
    levelOneProductCategoryNr: "ENTER NUMBER HERE",
    levelOneProductCategoryTitle: "ENTER HERE",
    levelTwoProductCategoryNr: "ENTER NUMBER HERE",
    levelTwoProductCategoryTitle: "ENTER HERE",
    levelThreeProductCategoryNr: "ENTER NUMBER HERE",
    levelThreeProductCategoryTitle: "ENTER HERE",
    levelFourProductCategoryNr: "ENTER NUMBER HERE",
    levelFourProductCategoryTitle: "ENTER HERE",
    levelFiveProductCategoryNr: "ENTER NUMBER HERE",
    levelFiveProductCategoryTitle: "ENTER HERE",
  },

  // =========================
  // TODO:  PRODUCT 009  TODO:
  // =========================

  {
    id: 8,
    imgSrc1: ".images/huawei_p50_pro_01.webp",
    imgSrc2: ".images/huawei_p50_pro_02.webp",
    imgSrc3: ".images/huawei_p50_pro_03.webp",
    imgSrc4: ".images/huawei_p50_pro_04.webp",
    productTitle: "HUAWEI P50 PRO",
    productDescriptionBrief:
      "Huawei P50 Pro Smartphone – 6.6”, 8GB, 256GB, 5-Lens Camera System, Black",
    currency: "R",
    productSellingPrice: 16500,
    imgSrcBrand: ".images/logo_huawei.webp",
    productBrand: "Huawei",
    productSku: "P50PRO",
    productModel: "P50PRO",
    itemsInStock: 3,
    LengthCm: 7.28,
    widthCm: 15.88,
    heightCm: 0.85,
    weightKg: 0.195,
    productDescriptionFull:
      "Huawei P50 Pro Smartphone (4G/LTE). CPU: ; GPU: ; SIM: ; SCREEN: ; MEMORY: ; STORAGE: ; EXTERNAL STORAGE: ; CAMERA(BACK): ; CAMERA(FRONT): ; CONNECTIVITY: ; OTHER/SENSORS: ; BATTERY: ; OPERATING SYSTEM: ; WARRANTY: ; COLOR: ; OPTIONAL: ",
    showProductOnSite: "NO",
    showPriceOnSite: "NO",
    itemOnSale: "NO",
    itemNewArrival: "NO",
    mainProductCategoryNr: "ENTER NUMBER HERE",
    mainProductCategoryTitle: "ENTER HERE",
    levelOneProductCategoryNr: "ENTER NUMBER HERE",
    levelOneProductCategoryTitle: "ENTER HERE",
    levelTwoProductCategoryNr: "ENTER NUMBER HERE",
    levelTwoProductCategoryTitle: "ENTER HERE",
    levelThreeProductCategoryNr: "ENTER NUMBER HERE",
    levelThreeProductCategoryTitle: "ENTER HERE",
    levelFourProductCategoryNr: "ENTER NUMBER HERE",
    levelFourProductCategoryTitle: "ENTER HERE",
    levelFiveProductCategoryNr: "ENTER NUMBER HERE",
    levelFiveProductCategoryTitle: "ENTER HERE",
  },

  // =========================
  // TODO:  PRODUCT 010  TODO:
  // =========================

  {
    id: 9,
    imgSrc1: ".images/huawei_watch_gt_runner_01.webp",
    imgSrc2: ".images/huawei_watch_gt_runner_02.webp",
    imgSrc3: ".images/huawei_watch_gt_runner_03.webp",
    imgSrc4: ".images/huawei_watch_gt_runner_04.webp",
    productTitle: "HUAWEI WATCH 3 GT RUNNER",
    productDescriptionBrief:
      "Huawei Watch 3 GT Runner – 1.43” AMOLED Touchscreen, IP68 Splash, Water (50m) and Dust Resistant, All-day Health Management, Black",
    currency: "R",
    productSellingPrice: 6650,
    imgSrcBrand: ".images/logo_huawei.webp",
    productBrand: "Huawei",
    productSku: "GTRun",
    productModel: "GTRun",
    itemsInStock: 6,
    LengthCm: 4.64,
    widthCm: 4.64,
    heightCm: 1.1,
    weightKg: 0.0385,
    productDescriptionFull:
      "Huawei Watch GT Runner. CPU: ; GPU: ; SIM: ; SCREEN: ; MEMORY: ; STORAGE: ; EXTERNAL STORAGE: ; CAMERA(BACK): ; CAMERA(FRONT): ; CONNECTIVITY: ; OTHER/SENSORS: ; BATTERY: ; OPERATING SYSTEM: ; WARRANTY: ; COLOR: ; OPTIONAL: ",
    showProductOnSite: "NO",
    showPriceOnSite: "NO",
    itemOnSale: "NO",
    itemNewArrival: "NO",
    mainProductCategoryNr: "ENTER NUMBER HERE",
    mainProductCategoryTitle: "ENTER HERE",
    levelOneProductCategoryNr: "ENTER NUMBER HERE",
    levelOneProductCategoryTitle: "ENTER HERE",
    levelTwoProductCategoryNr: "ENTER NUMBER HERE",
    levelTwoProductCategoryTitle: "ENTER HERE",
    levelThreeProductCategoryNr: "ENTER NUMBER HERE",
    levelThreeProductCategoryTitle: "ENTER HERE",
    levelFourProductCategoryNr: "ENTER NUMBER HERE",
    levelFourProductCategoryTitle: "ENTER HERE",
    levelFiveProductCategoryNr: "ENTER NUMBER HERE",
    levelFiveProductCategoryTitle: "ENTER HERE",
  },

  // =========================
  // TODO:  PRODUCT 011  TODO:
  // =========================

  {
    id: 10,
    imgSrc1: ".images/lenovo_p11_tablet_01.webp",
    imgSrc2: ".images/lenovo_p11_tablet_02.webp",
    imgSrc3: ".images/lenovo_p11_tablet_03.webp",
    imgSrc4: ".images/lenovo_p11_tablet_04.webp",
    productTitle: "LENOVO TAB P11",
    productDescriptionBrief:
      "Lenovo Tab P11 Tablet (TB-J606L) – 11” Touchscreen, 4GB, 128GB, Keyboard & Stylus Pen, 4G-LTE, Slate Grey",
    currency: "R",
    productSellingPrice: 7850,
    imgSrcBrand: ".images/logo_lenovo.webp",
    productBrand: "Lenovo",
    productSku: "TB-J606L",
    productModel: "TB-J606L",
    itemsInStock: 4,
    LengthCm: 16.3,
    widthCm: 25.84,
    heightCm: 0.75,
    weightKg: 0.49,
    productDescriptionFull:
      "Lenovo Tab P11 Tablet (TB-J606L / ZA7S0193ZA / 4G-LTE). CPU: ; GPU: ; SIM: ; SCREEN: ; MEMORY: ; STORAGE: ; EXTERNAL STORAGE: ; CAMERA(BACK): ; CAMERA(FRONT): ; CONNECTIVITY: ; OTHER/SENSORS: ; BATTERY: ; OPERATING SYSTEM: ; WARRANTY: ; COLOR: ; OPTIONAL: ",
    showProductOnSite: "NO",
    showPriceOnSite: "NO",
    itemOnSale: "NO",
    itemNewArrival: "NO",
    mainProductCategoryNr: "ENTER NUMBER HERE",
    mainProductCategoryTitle: "ENTER HERE",
    levelOneProductCategoryNr: "ENTER NUMBER HERE",
    levelOneProductCategoryTitle: "ENTER HERE",
    levelTwoProductCategoryNr: "ENTER NUMBER HERE",
    levelTwoProductCategoryTitle: "ENTER HERE",
    levelThreeProductCategoryNr: "ENTER NUMBER HERE",
    levelThreeProductCategoryTitle: "ENTER HERE",
    levelFourProductCategoryNr: "ENTER NUMBER HERE",
    levelFourProductCategoryTitle: "ENTER HERE",
    levelFiveProductCategoryNr: "ENTER NUMBER HERE",
    levelFiveProductCategoryTitle: "ENTER HERE",
  },

  // =========================
  // TODO:  PRODUCT 012  TODO:
  // =========================

  {
    id: 11,
    imgSrc1: ".images/lenovo_p15v_laptop_01.webp",
    imgSrc2: ".images/lenovo_p15v_laptop_01.webp",
    imgSrc3: ".images/lenovo_p15v_laptop_01.webp",
    imgSrc4: ".images/lenovo_p15v_laptop_01.webp",
    productTitle: "LENOVO THINKPAD P15V",
    productDescriptionBrief:
      "Lenovo Thinkpad P15V (Gen 2) Laptop – 15.6” FHD, Intel Core i9, 32GB, 1TB SSD, NVIDIA RTX A2000 GDDR6 (4GB), Windows 11",
    currency: "R",
    productSellingPrice: 56600,
    imgSrcBrand: ".images/logo_lenovo.webp",
    productBrand: "Lenovo",
    productSku: "P15V",
    productModel: "P15V",
    itemsInStock: 2,
    LengthCm: 25,
    widthCm: 36.65,
    heightCm: 2.42,
    weightKg: 2.07,
    productDescriptionFull:
      "Lenovo Thinkpad P15V (Gen 2) Laptop (21A9006YZA). CPU: ; GPU: ; SIM: ; SCREEN: ; MEMORY: ; STORAGE: ; EXTERNAL STORAGE: ; CAMERA(BACK): ; CAMERA(FRONT): ; CONNECTIVITY: ; OTHER/SENSORS: ; BATTERY: ; OPERATING SYSTEM: ; WARRANTY: ; COLOR: ; OPTIONAL: ",
    showProductOnSite: "NO",
    showPriceOnSite: "NO",
    itemOnSale: "NO",
    itemNewArrival: "NO",
    mainProductCategoryNr: "ENTER NUMBER HERE",
    mainProductCategoryTitle: "ENTER HERE",
    levelOneProductCategoryNr: "ENTER NUMBER HERE",
    levelOneProductCategoryTitle: "ENTER HERE",
    levelTwoProductCategoryNr: "ENTER NUMBER HERE",
    levelTwoProductCategoryTitle: "ENTER HERE",
    levelThreeProductCategoryNr: "ENTER NUMBER HERE",
    levelThreeProductCategoryTitle: "ENTER HERE",
    levelFourProductCategoryNr: "ENTER NUMBER HERE",
    levelFourProductCategoryTitle: "ENTER HERE",
    levelFiveProductCategoryNr: "ENTER NUMBER HERE",
    levelFiveProductCategoryTitle: "ENTER HERE",
  },

  // =========================
  // TODO:  PRODUCT 013  TODO:
  // =========================

  {
    id: 12,
    imgSrc1: ".images/samsung_galaxy_s22_ultra_01.webp",
    imgSrc2: ".images/samsung_galaxy_s22_ultra_02.webp",
    imgSrc3: ".images/samsung_galaxy_s22_ultra_03.webp",
    imgSrc4: ".images/samsung_galaxy_s22_ultra_04.webp",
    productTitle: "SAMSUNG GALAXY S22 ULTRA",
    productDescriptionBrief:
      "Samsung Galaxy S22 Ultra Phone (SM-S908) – 6.8”, 12GB, 256GB, 5-Lense Camera System, Black, LTE & 5G",
    currency: "R",
    productSellingPrice: 31750,
    imgSrcBrand: ".images/logo_samsung.webp",
    productBrand: "Samsung",
    productSku: "S22U",
    productModel: "S22U",
    itemsInStock: 1,
    LengthCm: 7.79,
    widthCm: 16.33,
    heightCm: 0.89,
    weightKg: 0.229,
    productDescriptionFull:
      "Samsung Galaxy S22 Ultra Phone (SM-S908). CPU: ; GPU: ; SIM: ; SCREEN: ; MEMORY: ; STORAGE: ; EXTERNAL STORAGE: ; CAMERA(BACK): ; CAMERA(FRONT): ; CONNECTIVITY: ; OTHER/SENSORS: ; BATTERY: ; OPERATING SYSTEM: ; WARRANTY: ; COLOR: ; OPTIONAL: ",
    showProductOnSite: "NO",
    showPriceOnSite: "NO",
    itemOnSale: "NO",
    itemNewArrival: "NO",
    mainProductCategoryNr: "ENTER NUMBER HERE",
    mainProductCategoryTitle: "ENTER HERE",
    levelOneProductCategoryNr: "ENTER NUMBER HERE",
    levelOneProductCategoryTitle: "ENTER HERE",
    levelTwoProductCategoryNr: "ENTER NUMBER HERE",
    levelTwoProductCategoryTitle: "ENTER HERE",
    levelThreeProductCategoryNr: "ENTER NUMBER HERE",
    levelThreeProductCategoryTitle: "ENTER HERE",
    levelFourProductCategoryNr: "ENTER NUMBER HERE",
    levelFourProductCategoryTitle: "ENTER HERE",
    levelFiveProductCategoryNr: "ENTER NUMBER HERE",
    levelFiveProductCategoryTitle: "ENTER HERE",
  },

  // =========================
  // TODO:  PRODUCT 014  TODO:
  // =========================

  {
    id: 13,
    imgSrc1: ".images/samsung_galaxy_tab_s8_ultra_01.webp",
    imgSrc2: ".images/samsung_galaxy_tab_s8_ultra_02.webp",
    imgSrc3: ".images/samsung_galaxy_tab_s8_ultra_03.webp",
    imgSrc4: ".images/samsung_galaxy_tab_s8_ultra_04.webp",
    productTitle: "GALAXY TAB S8 ULTRA",
    productDescriptionBrief:
      "Samsung Galaxy Tab S8 Ultra Tablet (SM-X906) – 14.6”, 12GB, 256GB, Keyboard & S-Pen, Black, LTE & 5G",
    currency: "R",
    productSellingPrice: 28250,
    imgSrcBrand: ".images/logo_samsung.webp",
    productBrand: "Samsung",
    productSku: "SM-X906",
    productModel: "SM-X906",
    itemsInStock: 8,
    LengthCm: 7.79,
    widthCm: 16.33,
    heightCm: 0.89,
    weightKg: 0.229,
    productDescriptionFull:
      "Samsung Galaxy Tab S8 Ultra Tablet (SM-X906). CPU: ; GPU: ; SIM: ; SCREEN: ; MEMORY: ; STORAGE: ; EXTERNAL STORAGE: ; CAMERA(BACK): ; CAMERA(FRONT): ; CONNECTIVITY: ; OTHER/SENSORS: ; BATTERY: ; OPERATING SYSTEM: ; WARRANTY: ; COLOR: ; OPTIONAL: ",
    showProductOnSite: "NO",
    showPriceOnSite: "NO",
    itemOnSale: "NO",
    itemNewArrival: "NO",
    mainProductCategoryNr: "ENTER NUMBER HERE",
    mainProductCategoryTitle: "ENTER HERE",
    levelOneProductCategoryNr: "ENTER NUMBER HERE",
    levelOneProductCategoryTitle: "ENTER HERE",
    levelTwoProductCategoryNr: "ENTER NUMBER HERE",
    levelTwoProductCategoryTitle: "ENTER HERE",
    levelThreeProductCategoryNr: "ENTER NUMBER HERE",
    levelThreeProductCategoryTitle: "ENTER HERE",
    levelFourProductCategoryNr: "ENTER NUMBER HERE",
    levelFourProductCategoryTitle: "ENTER HERE",
    levelFiveProductCategoryNr: "ENTER NUMBER HERE",
    levelFiveProductCategoryTitle: "ENTER HERE",
  },

  // =========================
  // TODO:  PRODUCT 015  TODO:
  // =========================

  {
    id: 14,
    imgSrc1: ".images/samsung_galaxy_watch_4_classic_01.webp",
    imgSrc2: ".images/samsung_galaxy_watch_4_classic_02.webp",
    imgSrc3: ".images/samsung_galaxy_watch_4_classic_03.webp",
    imgSrc4: ".images/samsung_galaxy_watch_4_classic_04.webp",
    productTitle: "GALAXY WATCH 4 CLASSIC",
    productDescriptionBrief:
      "Samsung Galaxy Watch 4 Classic (BSM-R895F) – 1.4” Super AMOLED Touchscreen, 46mm, Black, Wi-Fi & Bluetooth, LTE",
    currency: "R",
    productSellingPrice: 6850,
    imgSrcBrand: ".images/logo_samsung.webp",
    productBrand: "Samsung",
    productSku: "BSM-R895F",
    productModel: "BSM-R895F",
    itemsInStock: 5,
    LengthCm: 4.55,
    widthCm: 4.55,
    heightCm: 1.1,
    weightKg: 0.052,
    productDescriptionFull:
      "Samsung Galaxy Watch 4 Classic (BSM-R895F / LTE / 46mm). CPU: ; GPU: ; SIM: ; SCREEN: ; MEMORY: ; STORAGE: ; EXTERNAL STORAGE: ; CAMERA(BACK): ; CAMERA(FRONT): ; CONNECTIVITY: ; OTHER/SENSORS: ; BATTERY: ; OPERATING SYSTEM: ; WARRANTY: ; COLOR: ; OPTIONAL: ",
    showProductOnSite: "NO",
    showPriceOnSite: "NO",
    itemOnSale: "NO",
    itemNewArrival: "NO",
    mainProductCategoryNr: "ENTER NUMBER HERE",
    mainProductCategoryTitle: "ENTER HERE",
    levelOneProductCategoryNr: "ENTER NUMBER HERE",
    levelOneProductCategoryTitle: "ENTER HERE",
    levelTwoProductCategoryNr: "ENTER NUMBER HERE",
    levelTwoProductCategoryTitle: "ENTER HERE",
    levelThreeProductCategoryNr: "ENTER NUMBER HERE",
    levelThreeProductCategoryTitle: "ENTER HERE",
    levelFourProductCategoryNr: "ENTER NUMBER HERE",
    levelFourProductCategoryTitle: "ENTER HERE",
    levelFiveProductCategoryNr: "ENTER NUMBER HERE",
    levelFiveProductCategoryTitle: "ENTER HERE",
  },

  // ==============================================================================================================
  // FIXME:  END OF PRODUCTS IN THIS ARRAY
  // ==============================================================================================================
];
